# Generated by Django 5.0.9 on 2025-05-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('author', models.CharField(blank=True, null=True)),
                ('aquisition', models.DateField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, null=True)),
                ('num_page', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Biblio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genderbook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'Genderbook',
                'managed': False,
            },
        ),
    ]
